### ISSUE TITLE
Unknown device type id: 0

### ISSUE THREAD

**Issue by pixeldoc2000** [tfriedel/python-lightify#21]
I'm getting the following error with Home-Assistant 0.102.3 & 0.103.0 and my Osram Lightify Gateway (current FW).

2019-12-12 01:29:53 INFO (SyncWorker_5) [homeassistant.loader] Loaded osramlightify from homeassistant.components.osramlightify
2019-12-12 01:29:54 INFO (MainThread) [homeassistant.components.light] Setting up light.osramlightify
**2019-12-12 01:29:54 WARNING (SyncWorker_16) [lightify] Unknown device type id: 0. Please report to https://github.com/tfriedel/python-lightify**
2019-12-12 01:29:54 INFO (SyncWorker_16) [lightify] Initializing lightify, version=1.0.7.2

**Comment by OleksandrBerchenko** [comment]
Thanks for your report!  Several questions:
1. What device triggers this error?  Review your Lightify devices on Home Assistant UI and find the one that has "unknown device" in its `device name` attribute.  What is it?  Does it work correctly?
2. Did you see this error before, or only after some "trigger" like Gateway Firmware update?

**Comment by pixeldoc2000** [comment]
1. This is my Entitiy List with Lightify Devices in Home Assistant:
![grafik](https://user-images.githubusercontent.com/376715/70750455-c2ac6300-1d2e-11ea-96aa-48801ce47dce.png)
There are two devices that are showing with there Lightify id rather the a custom name configured via Lightify App. I'll have to check if these devices are still active.

This is a screenshot from my Lightify App:
![grafik](https://user-images.githubusercontent.com/376715/70750924-a4933280-1d2f-11ea-890c-0e1d13ea3a73.png)
There is an unknown device. Maybe thats causing the error in HA. I'm going the remove the unknown device and check if the error disappears.

2. I'm don't know at which point in time the error started to appear in the HA Log

**Comment by OleksandrBerchenko** [comment]
> There is an unknown device. Maybe thats causing the error in HA.

I'm sure it is.  If Osram Lightify can't identify a device, it probably sends "0" as its device type and HA plugin throws a warning.

Let me know whether removing that device fixes the issue or not.

Thanks!

**Comment by OleksandrBerchenko** [comment]
@pixeldoc2000 Have removing the unknown device from Osram Lightify app helped?

Thanks!

**Comment by pixeldoc2000** [comment]
@OleksandrBerchenko Yes.

Thx.

**Comment by OleksandrBerchenko** [comment]
A bit of off-topic: @pixeldoc2000, @tfriedel, have you updated your Lightify application with a mandatory Gateway firmware upgrade to version 1.5.1.0?  If yes, does this library still work as expected?  Especially when working with scenes?  Changelog says: "increased maximum number of 32 scenes".  To do that they would probably need to change binary offsets in API response.

Personally, I didn't upgrade firmware yet :)

Thanks!

**Comment by pixeldoc2000** [comment]
@OleksandrBerchenko yes, i'm running the latest gateway version, but i've not tested scenes.
![grafik](https://user-images.githubusercontent.com/376715/71493390-5eb19080-283e-11ea-841c-8e95fa46ce62.png)
