### ISSUE TITLE
Removed from PyPi?

### ISSUE THREAD

**Issue by dshokouhi** [tfriedel/python-lightify#22]
Is this just a PyPi error or something on my end?

https://pypi.org/project/lightify/

returns a 404 and `pip install lightify`

```
(homeassistant3.8) homeassistant@ubuntu:~/.homeassistant/custom_components$ pip install lightify==1.0.72
ERROR: Could not find a version that satisfies the requirement lightify==1.0.72 (from versions: none)
ERROR: No matching distribution found for lightify==1.0.72
WARNING: You are using pip version 20.2.1; however, version 21.0.1 is available.
You should consider upgrading via the '/srv/homeassistant3.8/bin/python3.8 -m pip install --upgrade pip' command.
```

**Comment by dshokouhi** [comment]
ahh seems the fix is incoming :)

https://github.com/home-assistant/core/pull/45775#issuecomment-770379144

**Comment by tfriedel** [comment]
Sorry about that, seems like the co-owner of the repo deleted it. I bumped the version number and submitted a new package to pypi.
