### ISSUE TITLE
Source tarball is missing for version 1.0.6.1

### ISSUE THREAD

**Issue by bachp** [tfriedel/python-lightify#5]
The release [1.0.6.1](https://pypi.python.org/pypi/lightify/1.0.6.1) is missing the tarball.
[1.0.6](https://pypi.python.org/pypi/lightify/1.0.6) had it.

**Comment by tfriedel** [comment]
thanks for noticing, I uploaded the tarball.
Also I didn't see your pull request for the licence fix before. That will be included in a next version.
